### ISSUE TITLE
[Bug] Files can't be loaded by traktor

### ISSUE THREAD

**Issue by Ma5onic** [axeldelafosse/stemgen#40]
I tried to load the generated stems but Traktor can't analyze them or load them.
Traktor Pro 3 Error:
![image](https://github.com/axeldelafosse/stemgen/assets/18509613/a699db73-c312-4696-bb9b-f241d64ed7ea)

Traktor Scratch Pro 2 Error:
![image](https://github.com/axeldelafosse/stemgen/assets/18509613/a020151b-48ed-4095-94c0-347533470943)

**Comment by Ma5onic** [comment]
I tried dumping the udta metadata using `mp4box --dump-udta 0:stem MyStemFile.stem.mp4`, as instructed in the NI File Specification PDF, but  got an error about too many arguments. dumping without `0:stem` did not generate a udta dump.
Possibly related to issue https://github.com/axeldelafosse/stemgen/issues/38:
The MP4 file must contain a box (i.e. data container) of type stem as a sub-box of
moov.udta. moov is the root box of the MP4 file, as shown in the Stem File Structure
diagram:
![image](https://github.com/axeldelafosse/stemgen/assets/18509613/52509850-a1c5-48d1-a6f0-ae6ea97e1c95)

**Comment by axeldelafosse** [comment]
Are you using Windows or macOS?

**Comment by Ma5onic** [comment]
Windows

**Comment by axeldelafosse** [comment]
Hey, sorry for the delay. This is related to https://github.com/axeldelafosse/stemgen/issues/19... I suspect an issue with https://github.com/NativeInstruments/ni-media, which probably doesn't support ALAC on Windows.

You can use the argument `-f aac` to force the compression to AAC instead of ALAC. This is pretty bad because you shouldn't be forced to compress your audio files. But if you really need to, I suggest using a good encoder like [qaac](https://stemgen.dev/docs/installation).
