### ISSUE TITLE
Creating wav stem.mp4 

### ISSUE THREAD

**Issue by Eve00000** [axeldelafosse/stemgen#50]
Hi, 
I like a lot what your wrote but .... as for the moment alac stems are not supported on windows, I'm trying to adapt your stem.pu script to create stem.mp4 files based on wav.
I'm suffering,because I can't find all the lines where you mentioned the conversion to m4a first.
Could you please publish a script for creating a stem.mp4 based on track.0.wav,  track.1.wav, track.2.wav, track.3.wav, track.4.wav, without converting them first to m4a.
Thank you,
Kind regards

**Comment by axeldelafosse** [comment]
Hey!

Thank you :)

You can refer to this comment: https://github.com/axeldelafosse/stemgen/issues/19#issuecomment-1616765584

If you want ALAC support on Windows, please make yourself heard in the forum: https://community.native-instruments.com/discussion/33853/lossless-stems

**Comment by Eve00000** [comment]
[Mixxx](Mixxx.org) dev team is working hard on stem integration and will support M4A stem files!

**Comment by axeldelafosse** [comment]
Amazing news! Love to hear it. At some point I forked the repo to implement this but couldn't justify the effort. Is there an issue or a PR to follow this work? Happy to help review. Thank you!

PS: I read in the past that there was an issue regarding the licensing of the stem file format... is this issue resolved?

**Comment by Eve00000** [comment]
I suppose you know Mixxx, well you can check [PR 13123](https://github.com/mixxxdj/mixxx/pull/13123).
With this PR and with ffmpeg and stem enabled in cmake Mixxx builds with stem support for M4A.
It's all in dev-phase, but I'm playing/testing around with it. 
Apparently the solution is in the ffmpeg. I suppose Traktor has constructed their software on the windows playersystem. 
I'm not the specialist, there are some real fantastic coding specialists making it marvelous, Antoine is doing it as a Google Summer of Code project,
You should check it out.
I quote DJ D-Town: 
M4A (aka MP4) is just a container and should be free of patents.
ALAC is royalty free (at least Apple as inventor of it, does not require any royalities): [](https://en.wikipedia.org/wiki/Apple_Lossless_Audio_Codec)
More difficult is the AAC codec, which exist with dozens of codec extensions added over time.
end quote
If you want more info or chat with these magnificent people, I can invite you to our [zulip chat.](https://mixxx.zulipchat.com/login/)

**Comment by axeldelafosse** [comment]
This is exciting! Thanks for sharing.

I re-read your first comment and realized that you were asking about creating a stem file containing WAVE stems instead of ALAC stems, right? This is not supported by Traktor so it's not supported by Stemgen.

I'm curious so I looked up Antoine's GitHub profile and found that he created another Stemgen: https://github.com/acolombier/stemgen -- which also supports ALAC or AAC stems only.

Hopefully Mixxx supports both ALAC and AAC to conform to the NI spec. It could theoretically support WAVE / AIFF / FLAC too but then the stem files won't be playable in Traktor.

**Comment by Eve00000** [comment]
You're welcome,
When you enter zuip you can read my post about my quest to generate the highest possible quality of stems, without artifacts....
I don't use stemgen to generate the different drums/bass/other/vox tracks, I tested a lot of generators and the quality / ease of use / speed of [Ultimate Vocal Remover](https://github.com/Anjok07/ultimatevocalremovergui) is a super trick, I just used your script to generate the combined stem files.
I wanted to test sound quality difference between m4a -> wav -> m4a and wav -> wav,
I am an audiophile. I tested with about 400 files :-)
PS: who the **** cares aboput traktor?

**Comment by axeldelafosse** [comment]
Interesting! Which model are you using with UVR? I might be able to use the same in Stemgen.

Note that if you are encoding WAVE to ALAC (or FLAC) -- it is a lossless compression so you won't lose any sound quality. Stemgen also support 24-bit audio files.

My favorite way to create stem files is when I have access to the multitracks directly. I can then generate the stem file from Ableton Live: https://stemgen.dev/docs/stemgen-for-ableton-live.

Otherwise when I'm not happy with Demucs, I use AudioShake.

**Comment by Eve00000** [comment]
Hi Axel,
Indeed I don't play lossy music, audience payis for mixed music in a quality they can't have at home so all ALAC (before it was all wav in a mega disc-rack).
UVR: Demucs - V4 httdemucs with GPU :-)
Earlier when I had connections in Belgian Public Radio I could have my a capella tracks easier.
![afbeelding](https://github.com/user-attachments/assets/bf299bf4-e375-43d1-8d38-f4ea5ade73ea)
