### ISSUE TITLE
GPU Support?

### ISSUE THREAD

**Issue by 0vm** [axeldelafosse/stemgen#8]
Since Demucs has GPU Support, Do you plan on adding it to this tool? Do you already have a way and just undocumented?

**Comment by awesomer** [comment]
Demucs uses the GPU by default if it's available. I would expect the stemgen wrapping of Demucs to Just Work if run in an environment (like WSL2 with GPU passthrough) with GPU available.

**Comment by 0vm** [comment]
hm thats odd, I already have it running in WSL2 with the Nvidia drivers installed with no luck, I'll try figuring it out, thank you.

**Comment by awesomer** [comment]
But as I understand it, demucs falls back to GPU automatically... why would
one deliberately want to default to CPU if the GPU is available?

**Comment by axeldelafosse** [comment]
To be honest, it's mostly a selfish decision because I don't have a Nvidia GPU so I chose to default to CPU. If you have a GPU you should use it! Except if you have low memory I guess, but you should try.

I haven't got any request about this so far but I'm obviously happy to default to GPU instead (and maybe let the underlying software fallback to CPU or introduce a flag to force CPU).

I was using Spleeter with the CPU package when I first created this script. It was a separate package for the GPU so this was the only option available. Now it seems to be unified but I unfortunately don't have an Nvidia GPU so I can't really test the GPU acceleration. Also I'd love to try to make Spleeter and/or Demucs work with Mac GPUs, maybe it could work with [Tensorflow Metal](https://developer.apple.com/metal/tensorflow-plugin/)?

Meta: I don't have any information about current users' needs. Please send me an email if you want to chat more about the future of Stemgen!
